### ISSUE TITLE
Possibility of running with older graphics stack

### ISSUE THREAD

**Issue by jomonjohnn** [lethal-guitar/RigelEngine#374]
I am new to Graphics programming hence asking this, Managed to build with gcc 7 on Xubuntu 18.04 using experimental/filesystem ( [patch](https://github.com/jomonjohnn/RigelEngine/commit/8ddadd5e70d24fd337ca0d2fd3dd6d5a3cb4ca86) ), but failed to run due the the GLSL version.

> ERROR: Shader compilation failed:
> 0:2(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Hence tried with USE_GL_ES=ON, 

> ERROR: Shader compilation failed:
> 0:14(1): error: No precision specified in this scope for type `vec2'
> 0:17(1): error: No precision specified in this scope for type `vec4'
> 0:19(1): error: No precision specified in this scope for type `vec4'
> 0:22(2): error: No precision specified in this scope for type `vec4'
> 0:23(2): error: No precision specified in this scope for type `vec4'
> 0:24(2): error: No precision specified in this scope for type `float

Adding glxinfo details, is it possible to run the game on this system somehow  ?

```
$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.2.8
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by lethal-guitar** [comment]
Hi @jomonjohnn, thanks for reporting! Huh, it seems odd that it wouldn't support GLSL 1.50 on your system, given that you seem to have support for OpenGL 4.2, and GLSL 1.50 was already introduced with OpenGL 3.2.

There's two things you could try: 

1. On [this line](https://github.com/lethal-guitar/RigelEngine/blob/0e579c52c277d92f6f64bd94c69022f75b06e4b6/src/renderer/renderer.cpp#L81), change the version from `150` to `130`. On my system, this works fine, and given your shader compiler output, it seems that `1.30` should be supported, so it might work for you as well.
2. When using GL ES, you could try adding a line `precision mediump float;` after [this line](https://github.com/lethal-guitar/RigelEngine/blob/0e579c52c277d92f6f64bd94c69022f75b06e4b6/src/renderer/renderer.cpp#L75). It seems that the precision specifier is mandatory for OpenGL ES, but I have only tested OpenGL ES on a Raspberry Pi so far, and it's GL implementation doesn't seem to care if it's missing.

Let me know if one of these two steps makes it work for you!

**Comment by jomonjohnn** [comment]
@lethal-guitar Thank you, it worked with option 1. 

> 1. On this line, change the version from 150 to 130. On my system, this works fine, and given your shader compiler output, it seems that 1.30 should be supported, so it might work for you as well.

didn't try the GL ES option yet. I will try the GL ES option after a code walk through

**Comment by lethal-guitar** [comment]
Sweet, glad to hear that it worked! It might make sense to drop the version down to 1.30 in general, as I'm not using any features specific to 1.50 as far as I know.

**Comment by lethal-guitar** [comment]
Ah, too bad, Mac OS X doesn't support GLSL 1.30, so we can't simply drop it down for everyone. It'd be a bit ugly, but I guess I could do something like:

```cpp
#ifdef __APPLE__

const auto SHADER_PREAMBLE = R"shd(
#version 150

#else

const auto SHADER_PREAMBLE = R"shd(
#version 130

// ...

#endif
```

**Comment by lethal-guitar** [comment]
@jomonjohnn I'm assuming it's okay to close this now, since you got it working by changing the version number. Feel free to reopen if you need more help.
