### ISSUE TITLE
Cannot build on Windows - VS 2019

### ISSUE THREAD

**Issue by s-martin** [lethal-guitar/RigelEngine#361]
I'm trying to build RigelEngine using Visual Studio 2019 16.1.1 under Windows 10 1809.

I get the following compilation errors

> 
> 7>D:\myprojects\RigelEngine\src\engine\shader.cpp(29,69): error C2440:  "Initialisierung": "initializer list" kann nicht in "rigel::engine::GlHandleWrapper" konvertiert werden 
> 7>D:\myprojects\RigelEngine\src\engine\shader.cpp(29,69): message :  Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig
> 7>D:\myprojects\RigelEngine\src\engine\shader.cpp(31,24): error C3536:  "shader": Kann nicht verwendet werden, bevor es initialisiert wurde.
> 7>D:\myprojects\RigelEngine\src\engine\shader.cpp(54,16): error C2440:  "return": "int" kann nicht in "rigel::engine::GlHandleWrapper" konvertiert werden
> 7>D:\myprojects\RigelEngine\src\engine\shader.cpp(54,16): message :  Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig
> 7>D:\myprojects\RigelEngine\src\engine\shader.cpp(65,13): error C2664:  "rigel::engine::GlHandleWrapper::GlHandleWrapper(rigel::engine::GlHandleWrapper &&)" : Konvertierung von Argument 2 von "PFNGLDELETEPROGRAMPROC" in "rigel::engine::GlHandleWrapper::DeleteFunc" nicht möglich

Currently I'm unable to get the reasons for this error.

**Comment by lethal-guitar** [comment]
Huh, weird, I did successfully compile it on VS 2019 on Windows 10, although I might have been using the 2017 toolset, I'd need to check. I'll have a look

**Comment by s-martin** [comment]
I'm using vcpkg to install Boost, SDL2 and SDL2 mixer, but that shouldn't make a difference.

**Comment by lethal-guitar** [comment]
I was still using VS 16.0.4, after I upgraded to 16.1.1, I did get build errors as well. I've opened https://github.com/lethal-guitar/RigelEngine/pull/368 to fix these.

Unfortunately, I wasn't able to reproduce the errors you got, which seem unrelated. I'm now using Visual Studio 2019, version 16.1.1, on Windows 10 Home v. 1903.

Here's a screenshot from my VS "about" dialog:
![grafik](https://user-images.githubusercontent.com/1821027/58630007-5a3fec00-82de-11e9-8874-7cacdc1b8f46.png)

So in order to fix your issue, I think we need to figure out what's different in your setup that could cause these errors. How did you invoke CMake?

**Comment by s-martin** [comment]
I've just seen your comment in the Readme regarding 64bit. 

So far I have only tried using 32bit, because all my installed libs like Boost etc. were already 32bit.
That could be the issue and I'll try 64 bit later.

As said before Boost, SDL2 and SDL mixer are installed using vcpkg, but I guess that shouldn't make a difference.

Are there any special requirements regarding installable VS components? Like a special version of the Windows SDK etc?

**Comment by s-martin** [comment]
Ok, works using x64.

Tests would not run, but I need to check that later (probably dll missing in the working dir).

**Comment by lethal-guitar** [comment]
> Ok, works using x64.

Nice! 👍 

> probably dll missing in the working dir

Yeah, you need to have the Boost and SDL DLLs in your `PATH`. I personally use a batch file which adds them to the path and then launches Visual Studio, but you could add them to your system path as well.

**Comment by pratikone** [comment]
@lethal-guitar  you can avoid adding Boost and SDL Dll in path for windows if you modify your cmake command to add those
`cmake .. -DWARNINGS_AS_ERRORS=OFF -DCMAKE_TOOLCHAIN_FILE=D:/github/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows`

**Comment by lethal-guitar** [comment]
Hi @pratikone, thanks for the info. When I wrote about setting the path, I wasn't aware that vcpkg automatically takes care of providing required DLLs. After fixing #370, I was able to generate a VS solution and run all executables from within Visual Studio, without having to set the path.

I specified neither the generator platform nor the target triplet, only the toolchain file, and I got a x64 solution out of the box. Maybe this was because I was using Visual Studio's "Native x64 tools" command prompt though? Do you think I should add the target triplet and platform arguments to the README?

**Comment by s-martin** [comment]
The latest VS2019 generator from CMake generates x64 by default now. For previous VS generators it's 32bit by default.
